set_property SRC_FILE_INFO {cfile:D:/PSN/porti_vhdl/not_gate/not_gate.srcs/constrs_1/new/test_not.xdc rfile:../../../not_gate.srcs/constrs_1/new/test_not.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports A]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Y]
